package bl4ckscor3.mod.globalxp;

import java.util.Arrays;

import bl4ckscor3.mod.globalxp.blocks.XPBlock;
import bl4ckscor3.mod.globalxp.network.ServerProxy;
import bl4ckscor3.mod.globalxp.network.packets.CPacketRequestXPBlockUpdate;
import bl4ckscor3.mod.globalxp.network.packets.SPacketUpdateXPBlock;
import bl4ckscor3.mod.globalxp.tileentity.TileEntityXPBlock;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInterModComms;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.relauncher.Side;

@Mod(modid=GlobalXP.modid, name=GlobalXP.name, version=GlobalXP.version, acceptedMinecraftVersions="[" + GlobalXP.mcVersion + "]")
public class GlobalXP
{
	public static final String modid = "globalxp";
	public static final String name = "Global XP";
	public static final String version = "v1.0";
	public static final String mcVersion = "1.11.2";
	public static Block xp_block;
	@SidedProxy(clientSide = "bl4ckscor3.mod.globalxp.network.ClientProxy", serverSide = "bl4ckscor3.mod.globalxp.network.ServerProxy")
	public static ServerProxy serverProxy;
	public static SimpleNetworkWrapper network;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		ModMetadata meta = event.getModMetadata();

		meta.authorList = Arrays.asList(new String[]{"bl4ckscor3"});
		meta.autogenerated = false;
		meta.description = "Adds a fast way to store XP and share it with your friends!";
		meta.modId = modid;
		meta.name = name;
		meta.version = version;
		network = NetworkRegistry.INSTANCE.newSimpleChannel(modid);
		network.registerMessage(new SPacketUpdateXPBlock.Handler(), SPacketUpdateXPBlock.class, 0, Side.CLIENT);
		network.registerMessage(new CPacketRequestXPBlockUpdate.Handler(), CPacketRequestXPBlockUpdate.class, 1, Side.SERVER);
		xp_block = new XPBlock(Material.IRON);
		GameRegistry.register(xp_block);
		GameRegistry.register(new ItemBlock(xp_block).setRegistryName(xp_block.getRegistryName().toString()));
		GameRegistry.registerTileEntity(TileEntityXPBlock.class, xp_block.getRegistryName().toString());
		serverProxy.loadModels();
		serverProxy.registerRenderers();
		GameRegistry.addRecipe(new ItemStack(xp_block, 1), "XXX", "XYX", "XXX", 'X', Blocks.IRON_BARS, 'Y', Items.EMERALD);
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		FMLInterModComms.sendMessage("waila", "register", "bl4ckscor3.mod.globalxp.imc.waila.WailaDataProvider.callbackRegister");
	}
}
