package bl4ckscor3.mod.globalxp;

import java.util.Arrays;

import bl4ckscor3.mod.globalxp.blocks.XPBlock;
import bl4ckscor3.mod.globalxp.itemblocks.ItemBlockXPBlock;
import bl4ckscor3.mod.globalxp.tileentity.TileEntityXPBlock;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInterModComms;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;

@Mod(modid=GlobalXP.MOD_ID, name=GlobalXP.NAME, version=GlobalXP.VERSION, acceptedMinecraftVersions="[" + GlobalXP.MC_VERSION + "]", guiFactory=GlobalXP.GUI_FACTORY)
@EventBusSubscriber
public class GlobalXP
{
	public static final String MOD_ID = "globalxp";
	public static final String NAME = "Global XP";
	public static final String VERSION = "v1.4.8";
	public static final String MC_VERSION = "1.12.2";
	public static final String GUI_FACTORY = "bl4ckscor3.mod.globalxp.gui.GUIFactory";
	public static Block xp_block;
	public static Config config;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		ModMetadata meta = event.getModMetadata();

		meta.authorList = Arrays.asList(new String[]{"bl4ckscor3"});
		meta.autogenerated = false;
		meta.description = "Adds a fast way to store XP and share it with your friends!";
		meta.modId = MOD_ID;
		meta.name = NAME;
		meta.version = VERSION;
		config = new Config(event.getSuggestedConfigurationFile());
	}

	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		FMLInterModComms.sendMessage("waila", "register", "bl4ckscor3.mod.globalxp.imc.waila.WailaDataProvider.callbackRegister");
		FMLInterModComms.sendFunctionMessage("theoneprobe", "getTheOneProbe", "bl4ckscor3.mod.globalxp.imc.top.GetTheOneProbe");
	}

	@SubscribeEvent
	public static void onRegisterBlocks(RegistryEvent.Register<Block> event)
	{
		event.getRegistry().register(xp_block = new XPBlock(Material.IRON));
		GameRegistry.registerTileEntity(TileEntityXPBlock.class, xp_block.getRegistryName());
	}

	@SubscribeEvent
	public static void onRegisterItems(RegistryEvent.Register<Item> event)
	{
		event.getRegistry().register(new ItemBlockXPBlock(xp_block).setRegistryName(xp_block.getRegistryName().toString()));
	}
}
