# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version = 1.21.11
loader_version = 0.17.3

# Mod Properties
mod_version=1.12.2
maven_group=bl4ckscor3.mod
archives_base_name=globalxp-fabric-1.21.11

# Dependencies
fabric_version=0.139.5+1.21.11
cloth_config_version = 21.11.150
modmenu_version = 17.0.0-alpha.1
jade_version=7312559
wthit_version=7312785
badpackets_version=7312680