# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version = 1.20.6
loader_version = 0.16.2

# Mod Properties
mod_version=1.12
maven_group=bl4ckscor3.mod
archives_base_name=globalxp-fabric-1.20.6

# Dependencies
fabric_version = 0.100.8+1.20.6
jade_version=5366607
wthit_version=5568794
badpackets_version=5400299
cloth_config_version = 14.0.129
modmenu_version = 10.0.0