# Project
group=bl4ckscor3.mod.globalxp
version=1.13
minecraft_version=26.1.1
java_version=25
license=MIT
mod_id=globalxp
mod_name=Global XP
description=Adds a fast way to store XP and share it with your friends!
mod_author=bl4ckscor3
minecraft_version_range=[26,)
source_link=https://github.com/bl4ckscor3/GlobalXP
cf_link=https://www.curseforge.com/minecraft/mc-mods/global-xp

# Common
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.1-1
mdg_version=2.0.141
fcap_version=26.1.3
run_dir=../runs
mixin_version=0.13.3+mixin.0.8.5
mixinextras_version=0.3.5

# NeoForge
neoforge_version=26.1.1.10-beta
neoforge_jade_version=7817285
neoforge_wthit_version=7880673
neoforge_badpackets_version=7878544

# Fabric
loom_version=1.15-SNAPSHOT
fabric_version=0.145.3+26.1.1
fabric_loader_version=0.18.6
modmenu_version=18.0.0-alpha.8
fabric_jade_version=7862100
fabric_wthit_version=7880671
fabric_badpackets_version=7878543

# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
